### ISSUE TITLE
SMART CONTRACT: Build create borrow Proposal 

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#14]
The underlying mechanism is that when the user looks through the platform and doesn't find a suitable interest apy that they are interested in or the token they want to borrow,  they can create a borrow proposal with the following parameters:

- Token to borrow or lend
- specific amount of tokens that they want to borrow
- their borrow duration until they have to pay back
- their range of interest APY 

when you are assigned, please ping me on TG at [t.me/DProf_in_tech](url) to discuss the specifics of this issue.

**Comment by Iwueseiter** [comment]
Hi @Dprof-in-tech can I work on this?

**Comment by ShantelPeters** [comment]
Let me handle this issue ? I will create a user-friendly interface that allows users to submit a borrow proposal by selecting the token, specifying the amount, defining the borrow duration, and setting their desired interest APY range. The submitted proposals will be processed and saved in the system for visibility to other users.

**Comment by kfastov** [comment]
May I handle this issue?
I am a full stack web3 developer with an experience in writing Cairo smart contracts and contributing in open source projects.
I would develop a data type for the borrow proposal with all specified fields and then develop a smart contract based on a discussed specifics of this issue

**Comment by Dprof-in-tech** [comment]
This issue has been decommisioned  for some internal deliberation.
Thank you all.
