### ISSUE TITLE
Blog Page Text Not Visible in Dark Mode

### ISSUE THREAD

**Issue by Jagadeeshftw** [Peerprotocol/peer-on-strk#40]
I encountered an issue on the blog page of the website while using the dark theme. The text content on the blog page becomes extremely difficult to read due to improper background colour settings.
![image](https://github.com/user-attachments/assets/7453ed89-378a-4553-adca-83c6d4fb18a8)

**Comment by Jagadeeshftw** [comment]
I would like to work on resolving this issue. Please let me know if I can take this up.

**Comment by Dprof-in-tech** [comment]
This issue is open to be assigned for a fix by when the OD Hack starts, so please if you haven't done so yet, register for the od hack and apply thorugh OnlyDust for this

**Comment by codebestia** [comment]
Mind if I try this one?

**Comment by OWK50GA** [comment]
Could I take a shot at this?
I will go through the text display and edit the font colour, possibly style and size to make it easy to read.

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by CollinsC1O** [comment]
May I be assigned to this?

**Comment by SYLVIANNORUKA** [comment]
Is it okay if I tackle this?
I am a Front-end  developer 
Use a ThemeContext to set a suitable background when you switch to dark mode and vice versa for light mode

**Comment by JP-the-Analyst** [comment]
Hello.
I'd love to contribute to this task as it aligns with my skill and interest in improving user experience. I understand that the crux of the issue involves fixing the background colour settings on the blog page to ensure readability, especially when using the dark theme. This is but a basic issue i can handle, and I'm looking forward to contributing to the project.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity and web dev
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by Dprof-in-tech** [comment]
Gm guys, so i just looked through and this problem had already been fixed way before now do i'm gonna be closing this issue
