### ISSUE TITLE
CONTRACTS:  Build a function to allow users create a Lending proposal

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#41]
So this Lending proposal is just like p2p buyer or seller ads on your exchange where you can say, hey i have this token to be borrowed, and stuff like that. so build a cairo function that allows this to be created withh the following specifics.

<img width="1512" alt="Screenshot 2024-11-21 at 06 33 42" src="https://github.com/user-attachments/assets/d1358efc-5307-4900-9a42-de8965db2469">

this function should write the following details into the contract and store them

the token the lender has to offer ( for now can only be ETH or Strk)
the quantity they have to offer
the lenders preferred interest rate (cannot be more than 7%)
the duration of this loan before repayment (not less than 7 days and not more than 15 days)
the lenders address as the creator
the date when this proposal was created.

there should also be a read function to read this data so that it can be displayed in the right page for the borrowers to see and also write tests for this function.

Criteria to be assigned an issue:

follow the steps as given in the ODhackers community group.

when applying, please give a reasonable ETA for sending in a solution to this issue.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >48 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by omsant02** [comment]
Would love to tackle this!

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. 

I can implement this issue and ensure the functionality behaves as expected by writing a robust test.

ETA - 3 days

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by jsanchez556** [comment]
Hi,  my name is José Mario from Costa Rica, a Full stack developer with more than 15 years in development and a focus in TypeScript, JavaScript, Nodejs and React. Open Source projects are something I enjoy, and I am now learning on Rust, and Cairo, I recently contribute to some Rust projects. About my learning and growth in the industry, I started doing ODHacks as early as version 7.0 due to my work with Dojo Coding. I am excited to utilize my wealth of experience and experience to new technologies to meet new challenges and deliver results.

How to tackle this feature:

Create function that validates and stores proposal data (token, quantity, interest rate, duration, lender address, creation date) and another function to retrieve the proposals, finally create test cases to validate the feature.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >48 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by SoarinSkySagar** [comment]
May i work on this @Dprof-in-tech?

eta: 3 days

**Comment by casweeney** [comment]
## Tackling this issue:

Given the UI, I can see that this function `create_lending_proposal()` will take in `quantity`, `duration` and `interest_rate` as function arguments.

I will implement this function ASAP.

## ETA: 6 hours.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by mimiprosper** [comment]
Could I try solving this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by aspiringLilCoder** [comment]
Can I take this from here?

**Comment by Aditya-040** [comment]
Can I try solving this issue?

**Comment by Akshola00** [comment]
**Application for Lending Proposal Function Issue**

**Introduction**  
Hello Team,  
I am excited to develop the lending proposal feature for peer-to-peer loan offers. With my experience in smart contract development and StarkNet, I can create a strong and efficient solution that ensures smooth borrowing experiences.

How I Will Solve the Issue
To complete this task, I will create a Cairo function to store essential details about the lending proposal, including the token type (ETH or STRK), quantity, interest rate (max 7%), loan duration (7 to 15 days), lender’s address, and creation date. I will also add a read function for easy access to this information.

**Comment by Akshola00** [comment]
I am excited to develop the lending proposal feature for peer-to-peer loan offers. With my experience in smart contract development and StarkNet, I can create a strong and efficient solution that ensures smooth borrowing experiences.

How I Will Solve the Issue
To complete this task, I will create a Cairo function to store essential details about the lending proposal, including the token type (ETH or STRK), quantity, interest rate (max 7%), loan duration (7 to 15 days), lender’s address, and creation date. I will also add a read function for easy access to this information.

eta <1day

**Comment by Snehagupta1907** [comment]
I'd be happy to do this.

**Comment by Dprof-in-tech** [comment]
@aspiringLilCoder 
i saw your contributions to BuildGuidl and decided to assign ths to you. Please reach out if you are stuck and be sure to send a draft PR in 12 hrs

**Comment by Dprof-in-tech** [comment]
@aspiringLilCoder , please you have one hour to make a draft PR or you will be unassigned.

**Comment by omsant02** [comment]
can i take this issue @Dprof-in-tech ?
would solve it in 5-6 hrs

**Comment by martinvibes** [comment]
hey @Dprof-in-tech i'm creating a PR in 30min

**Comment by martinvibes** [comment]
hey @Dprof-in-tech please kindly re-assign i'm almost done
