### ISSUE TITLE
CONTRACTS:  Build a function to allow users create a counter proposal to a lending proposal

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#42]
see issue #41  to see what a lending proposal is.

creating a counter proposal is in the situation where a borrower sees a lending proposal that they love but dont want to accept maybe because the number of tokens to be lent is too high or too low, then they can create a proposal to counter it and say, this is the exact things i can take and if the lender is willing, they can move on.

<img width="1512" alt="Screenshot 2024-11-21 at 06 36 29" src="https://github.com/user-attachments/assets/fb60aa51-1e05-4db3-b983-bbfb4fadb9c4">

this function should take similar parameters just like in issue #41 and there should also be a read function to read this data after writing it into the blockchain. 

Criteria to be assigned:

follow the guidelines as put in the OD hackers community group.

Please when applying give a reasonable ETA

**Comment by omsant02** [comment]
May I handle this issue?

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by hannahredler** [comment]
Hey! Im a full stack dev, with a few years of experience in web3, although fairly new to Cairo. I would appreciate the chance to work on this task!

Since the task seems to be similar to a function that already exists, I think it is simply a matter of checking the previous implementation, and adapting it to the new use case. In addition, adding a function to read the counter proposal.

I predict approx. 2 days to work on this issue.

**Comment by SoarinSkySagar** [comment]
May I work on this issue @Dprof-in-tech?

eta: 3 days

**Comment by JoE11-y** [comment]
Can I take care of this issue?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by mimiprosper** [comment]
Could I try solving this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by aspiringLilCoder** [comment]
Can I work on this, please?

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by Aditya-040** [comment]
Mind if I take this issue?

**Comment by Dprof-in-tech** [comment]
@mimiprosper , please you have one hour to make a draft PR or you will be unassigned.

**Comment by omsant02** [comment]
can i take this issue @Dprof-in-tech ?
would solve it in 5-6 hrs
