### ISSUE TITLE
CONTRACTS: Build a function to allow lenders or borrowers accept or reject a proposal

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#43]
write a function that allows users to accept proposals created in the system.

This function would flow as:

check the type of proposal and check that the acceptor is not the creator.
write a function to check that the acceptors available balance in the  protocol is 1.3 times greater than what he's about to borrow (for borrower) and check that lender has  more than the amount to be lent in the protocol.
build a function that for borrower, locks the equivalent of 1.3x the amount he's borrowing in the platform so that they can't access these funds until what they owe is paid.
for lender, write a function that transfers the required amount to the borrower's address when they accept this proposal and everything is okay.
mint a spoke (little NFT) for both lender and borrowers as a proof of action on the platform that gets sent to their wallets and is used to validate repayment options.

record the time this was accepted and the expected repayment date and also the interest rates and all. 
charge a 1% fee that goes to the protocol for every accepted proposal.

write this transaction into the transaction history with a transaction type of lend or borrow.

criteria to be assigned:

follow the guidelines as given in the OD Hackers community.

please while applying, give a reasonable ETA

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of Cairo code base. I would love to work on this.

ETA - 2days

**Comment by hannahredler** [comment]
Hey! Im a full stack dev, with a few years of experience in web3, although fairly new to Cairo. I would appreciate the chance to work on this task!

I would follow the criteria stated one by one, testing and ensuring each is hit. My ETA is ~3 days (a generous estimate to ensure rigorous testing).

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by SoarinSkySagar** [comment]
May I work on this issue @Dprof-in-tech?

eta: 4 days

**Comment by od-hunter** [comment]
Hello, can I be assigned this please? I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, solidity and cairo.

To solve this issue I’ll take the following steps:
1.⁠ ⁠I’ll implement an acceptProposal function to handle proposal acceptance, managing both borrower and lender scenarios.
2.⁠ ⁠⁠Then check proposal type (lend or borrow) using a conditional logic structure. I’ll ensure the acceptor is not the creator of the proposal.
3.⁠ ⁠⁠So, for borrowers, I’ll deduct 1.3x the proposal amount from their balance and lock it in the protocol.
Fund Transfers. Then for lenders, I’ll debit the lending amount from their balance and credit it to the borrower's account.
4.⁠ ⁠I’ll introduce a function mintNFT, for both borrower and lender as proof of action. I’ll also calculate and deduct a 1% fee from the proposal amount, crediting it to the protocol's balance.
5.⁠ ⁠⁠I’ll use events (ProposalAccepted, NFTMinted) to track and log significant actions in the system.

Please assign me I’m ready to work.

**Comment by casweeney** [comment]
## Tackling this issue

- Given that I understand how lending and borrowing works, I can tackle this issue. To accept or reject proposal requires that proposal already exist.

- Also I pretty much understand this codebase, I can easily sync with it.

**Comment by Supa-mega** [comment]
Mind if I take this issue?

**Comment by mimiprosper** [comment]
I'd be happy to do this.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by Dprof-in-tech** [comment]
@casweeney , please you have four hours to make a draft PR or you will be unassigned.

**Comment by casweeney** [comment]
@Dprof-in-tech PR created: https://github.com/Peerprotocol/peer-on-strk/pull/57
