### ISSUE TITLE
CONTRACTS: Build a function to allow users create a borrow proposal

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#44]
same thing as issue #41 except this time, its more like i want to borrow these tokens instead of lending them out.

takes same information as in issue #41 

criteria to be assigned:

please follow the guidelines as given on the OD Hackers community

also, when applying please give an ETA

**Comment by Pvsaint** [comment]
Assign me this issue please, I can deliver within 48hrs

**Comment by CollinsC1O** [comment]
Hello @Dprof-in-tech I'm a front-end and a blockchain developer. I will love to take on this

**Comment by Mystic-Nayy** [comment]
@Dprof-in-tech Can i work on this?
ETA 24 hours after being assigned

**Comment by omsant02** [comment]
I'd like to handle this task.

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You 
ETA; 48 hours

**Comment by SoarinSkySagar** [comment]
May I work on this @Dprof-in-tech?

I am an experienced Cairo developer and a regular contributor at @keep-starknet-strange and I am confident that I can resolve this.

eta: 3 days

**Comment by casweeney** [comment]
### I will really like to tackle this issue

### Tackling the issue:
- I will implement a function `create_proposal()` that enables users to create a proposal.

**Comment by Supa-mega** [comment]
I’d love to work on this task.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by mimiprosper** [comment]
I'd like to take this issue.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by aspiringLilCoder** [comment]
Can I contribute to this one?

**Comment by Aditya-040** [comment]
Is this issue still available?

**Comment by Ndifreke000** [comment]
Clear on the requirements! ETA for the solution: 3 days.

**Comment by aniruddhaaps** [comment]
To implement the borrowing functionality for users to borrow tokens:

Backend Development:

Create the API endpoint that allows a user to create borrowing proposals. This may include information such as token type, borrowing amount, interest rate, repayment time, and collateral detail.
Frontend Integration:

Add a "Borrow Tokens" form on the relevant page that collects and sends all this information over to the backend.
Ensure clarity between the "Borrow" and "Lend" functionalities on the user interface.
Testing:

Write unit tests for the backend logic to validate data handling and proposal creation.
Integration tests should be written to verify that the form submission works seamlessly with the backend.

**Comment by Akshola00** [comment]
I woul like to help address the token borrowing issue. With my background in blockchain development and smart contracts, I understand how to create secure systems for borrowing tokens. 

How I Will Solve the Issue

I will implement a borrowing mechanism that aligns with the lending functionality described. This will include proper collateral, interest rate calculations, and repayment schedules.
I will follow ensure compatibility and scalability, and thoroughly test my solution to ensure it works reliably.

**Comment by Akshola00** [comment]
I woul like to help address the token borrowing issue. With my background in blockchain development and smart contracts, I understand how to create secure systems for borrowing tokens. 

How I Will Solve the Issue

I will implement a borrowing mechanism that aligns with the lending functionality described. This will include proper collateral, interest rate calculations, and repayment schedules.
I will follow ensure compatibility and scalability, and thoroughly test my solution to ensure it works reliably.

eta < 1day

**Comment by Snehagupta1907** [comment]
Mind if I try this one?

**Comment by Iwueseiter** [comment]
Mind if I take this issue?
