### ISSUE TITLE
CONTRACTS: Build a function to repay loans

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#46]
this function would be tied to the repay button created in issue #45 so that a user can repay their loans from the position over view page.

this function should enable users pay back their loans including the interest rates, then transfer the paid back loan to the lender with their interest, send the service charge to the protocol and mark the position as closed and deal completed.

Criteria to be assigned:

please follow the guidelines as given in the OD Hackers community

also, when applying, do give a reasonable ETA

**Comment by ikemHood** [comment]
looking to take on this as soon as ODHack starts @Dprof-in-tech

**Comment by raizo07** [comment]
May I take care of this? I',m a Software developer with over four years of experience and I've contributed to a couple of projects on OnlyDust

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. I would love to work on this.

ETA - 2days

**Comment by GideonBature** [comment]
Can this issue be assigned to me please?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contract, using Cairo.  If given this issue, I should be able to send my first PR within 72 hrs. 

Thank you!

**Comment by Birdmannn** [comment]
My name is Pascal Torti, a recent graduate from the cairo bootcamp. I would love to hop on this issue to demonstrate the skills acquired in the last few months. It may feel "medium", but there is nothing I can't deliver on. P.S. I do java

**Comment by SoarinSkySagar** [comment]
May i work on this issue @Dprof-in-tech?

my approach: I would get the loan amount and interest rate, then calculate it and transfer it to the lender, along with the service fee to the protocol. Then the position can be closed.

eta: 3 days

**Comment by casweeney** [comment]
## Tackling this issue:

- I will study existing lending & borrowing protocol to understand how they implement this feature, I will then implement the `repay_loan()` function.

**Comment by Supa-mega** [comment]
I'd love to work on this!

**Comment by augustin-v** [comment]
Hello I'd love to work on this. I have experience with Cairo contributing to Kakarot.
I'll make sure to communicate if I encounter any problem along the way.
ETA: 3 days

**Comment by mimiprosper** [comment]
Could I take on this issue?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by blessingbytes** [comment]
I am a frontend and blockchain developer specializing in creating intuitive user interfaces . I have experience with modern frameworks like React and smart contract development on platforms like Ethereum and Starknet.

Pls, i would love to tackle this issue. ETA => 48hrs

**Comment by wheval** [comment]
Hello, I'm wheval a frontend dev and Cairo programmer.
I would implement a repay() function that pays the protocol and lenders at the interest rates.
I would also emit an event that communicates the state of the loan and can be watched from the front end.

ETA is 2 days.

**Comment by aniruddhaaps** [comment]
To implement the repay functionality associated with the "Repay" button:

Develop a function to compute the total amount for repayment (principal + interest), subtract it from the user's wallet, and transfer the same to the lender and protocol for service charge.
Update the loan status in the database to "closed" while making sure that the position is marked as completed.
Follow all the guidelines of the OD Hackers community, and the ETA is 2-3 days, considering the integration complexity with both payment and database systems.

ETA- 2 days

**Comment by Snehagupta1907** [comment]
May i take up this issue 
I am a software developetr have worked on contracts related to rentals and repay contracts too so i haev a fair idea.
ETA:2-3 days

**Comment by 3th-Enjay** [comment]
May I pick this up? here is how I the logic I would use to approach this issue.  
Calculate Total Repayment Amount,
Ensure the user has sufficient funds to cover the repayment including the interest on the loans.
create a function to transfer Funds to the lender. then mark the loan position as closed and the deal as completed. finally handle cases like insufficient funds, failed transfers, or unexpected errors gracefully.

**Comment by Birdmannn** [comment]
Hey @Dprof-in-tech 
My name is Pascal Torti, I have expertise in java Springboot, JavaScript and Cairo Starknet. I have confidence in my skills, and hope my skills are implored on to fulfil the closing of this issue.

I have read the guidelines of the OD hack community, and I have gone through your repo, and I have seen I can ass a new function to the peer protocol interface and implement it in the main contract class. I shall also carry out all possible tests on that function to ensure that it works efficiently. And I'll make sure while adding the function, I won't tamper with other existing functionalities. 

ETA to achieve this is maximum of 3 days. I'm sure it would be less, I gave room for other uncertain concerns. Thank you

**Comment by martinvibes** [comment]
hey can i work on this

**Comment by saimeunt** [comment]
Hey I'd like to work on this one, see my past Cairo experiences here: https://app.onlydust.com/u/saimeunt
I will study how to implement this feature by getting inspiration from similar projects and complete it in 2 days.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by Dprof-in-tech** [comment]
@saimeunt , please you are expected to mke a draft PR in 12 hours, if you have any blockers, kindly reach out to me on Telegram. Thank you.
