### ISSUE TITLE
FE: Build quest welcome page

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#48]
https://www.figma.com/design/iW3cyAME5y74CegO0726ki/peer.protocol-quests?m=auto&t=SCxMYzYz92hgX4z3-1

here's the link to the figma and your job is to replicate exactly the quests welcome page.
The side bar is already built out and can be found in the /frontend/app/app folder. kindly import it and  add a nav link to the quests welcome page. Don't forget to make it mobile responsive too..

Criteria to be assigned:

follow the guidelines as given in the Od Hackers community group and dont forget to provide an ETA when applying

**Comment by martinvibes** [comment]
Could I grab this task?
i'm a frontend dev and i would love to take on this issue

**Comment by omsant02** [comment]
Is this issue still available?

**Comment by CollinsC1O** [comment]
May I take care of this?

**Comment by wheval** [comment]
Hello @Dprof-in-tech, I'm Wheval a  frontend developer with multiple experiences working with Nextjs and TypeScript. Can i work on this?

I would ensure I create a pixel-perfect replica of the Figma. 
I would also ensure it is responsive and follows the current structure of the codebase.

ETA is 2 days.

**Comment by 0xdevcollins** [comment]
Could I grab this task?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

ETA: 24hrs

**Comment by ShantelPeters** [comment]
I’d like to work on this.

**Comment by Akshola00** [comment]
I’d love to work on this task.

**Comment by Aditya-040** [comment]
May I pick this up? I am a fullstack developer love to contribute on this

**Comment by jancris100** [comment]
Could I grab this task? Im from dojo coding I have two years of experience as full stack developer im actually work with figma to mobile apps

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga
ETA: 2 days

**Comment by ONEONUORA** [comment]
Can I be assigned to this?

**Comment by Amarjeet325** [comment]
I'd like to take this issue.

**Comment by JoelVR17** [comment]
## I'm Joel Vargas, and I'm a Frontend Developer
## Dojo Coding 🔥

# Implement Quests Welcome Page

## Description
Replicate the **Quests Welcome Page** as per the Figma design provided. Ensure the page matches the design perfectly and is fully responsive. Import the pre-built sidebar from `/frontend/app/app` and include a navigation link to the **Quests Welcome Page** in the sidebar.

---

## Requirements

### 1. **Page Layout**
- Recreate the **Quests Welcome Page** based on the Figma design.
- Integrate the pre-built sidebar into the page layout.
- Add a navigation link to the **Quests Welcome Page** in the sidebar.

### 2. **Responsive Design**
- Ensure the page is responsive across all screen sizes:
  - Desktop
  - Tablets
  - Mobile devices

### 3. **Design Consistency**
- Match the Figma design, ensuring:
  - Accurate typography
  - Consistent spacing and colors
  - Button styles with hover effects

### 4. **Functional Components**
- Implement all interactive elements such as:
  - Navigation links
  - Buttons
  - Animations or transitions (if applicable)

---

## Tasks

1. **Setup**
   - Import the sidebar from `/frontend/app/app`.
   - Add a navigation link to the **Quests Welcome Page** in the sidebar.

2. **Layout**
   - Create the structure of the **Quests Welcome Page** as shown in the Figma design.

3. **Styling**
   - Apply styles to replicate the Figma design exactly.
   - Include hover states, animations, or transitions as per the design.

4. **Responsiveness**
   - Use CSS or responsive frameworks to ensure the page adapts to all screen sizes.

5. **Testing**
   - Verify the layout and functionality across devices and browsers.

6. **Final Review**
   - Ensure the design matches the Figma mockup pixel-perfectly.
   - Validate that the navigation link is working correctly.

---

## ETA
Estimated timeline for completion:
- **Sidebar integration and navigation link**: ~1 hour
- **Layout and structure**: ~3 hours
- **Styling and animations**: ~3-4 hours
- **Responsiveness and testing**: ~2-3 hours
- **Final review and fixes**: ~1 hour

**Total ETA**: ~9-12 hours depending on complexity.

---

## Acceptance Criteria
- The **Quests Welcome Page** matches the Figma design exactly.
- The page is fully responsive and works across all devices.
- The sidebar is functional with a navigation link to the **Quests Welcome Page**.
- The implementation follows the Od Hackers community group guidelines.

---

### Additional Notes
For any clarifications, refer to the Od Hackers community guidelines or contact the project manager.

**Comment by akintola4** [comment]
Can I handle this task?i would love to build it , this is my  twitter account for my works https://x.com/photofola

**Comment by akintola4** [comment]
Can I handle this task?i would love to build it , this is my  twitter account for my works https://x.com/photofola and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by Kaminar-i** [comment]
Can I handle this task?

**Comment by SudiptaPaul-31** [comment]
Can I jump on this task?

**Comment by SudiptaPaul-31** [comment]
May I take this issue on?

My approach:

Will verify the figma file and make the designing accordingly and making sure that its responsive the mobile view should like the one in the figma file.


ETA-2Days

**Comment by aspiringLilCoder** [comment]
Is this issue still available?

**Comment by David-Maduabuchi** [comment]
Hello @Dprof-in-tech, I'm David a frontend developer with multiple experiences working with Nextjs and TypeScript. Can i work on this?

I would ensure I create a pixel-perfect replica of the Figma.
I would also ensure it is responsive and follows the current structure of the codebase.

ETA is 2 days.

**Comment by Dprof-in-tech** [comment]
@Amarjeet325 , please you have one hour to make a draft PR or you will be unassigned.
