### ISSUE TITLE
FE: Build out the Social quests page

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#49]
https://www.figma.com/design/iW3cyAME5y74CegO0726ki/peer.protocol-quests?m=auto&t=SCxMYzYz92hgX4z3-1

here's the link to the figma and your job is to replicate exactly the social quests page.
The side bar is already built out and can be found in the /frontend/app/app folder. kindly import it in the page. Don't forget to make it mobile responsive too..

Criteria to be assigned:

follow the guidelines as given in the Od Hackers community group and dont forget to provide an ETA when applying

**Comment by martinvibes** [comment]
I’d love to work on this task.
please kindly assign :)

**Comment by omsant02** [comment]
Can I be assigned to this?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. This is my first time contributing this project.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by 0xdevcollins** [comment]
Can I handle this task?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

ETA: 24hrs

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.
Plan to Address the Requirements

1. Analyze the Figma Design
	•	Thoroughly review the Figma link to ensure all elements are captured, including layout, styles, typography, and interactions.

2. Integrate the Existing Sidebar
	•	Import the already-built sidebar from /frontend/app/app and integrate it into the Social Quests page seamlessly.

3. Build the Page Layout
	•	Use TailwindCSS for styling, ensuring a pixel-perfect design based on the Figma reference.
	•	Structure the page with modular, reusable components for maintainability.
	•	Implement the design with focus on user experience and adherence to the design details.

4. Ensure Mobile Responsiveness
	•	Use TailwindCSS’s responsive utilities to make the design adapt to various screen sizes.
	•	Test the layout on multiple devices to ensure usability and a consistent look.

5. Follow Od Hackers Guidelines
	•	Reference the community group’s style and technical guidelines throughout the implementation to ensure compliance.

6. Provide Deliverables
	•	A fully functional, responsive Social Quests page that matches the Figma design.
	•	Reusable components for ease of maintenance.
	•	Compatibility with the existing codebase.

**Comment by zintarh** [comment]
Mind if I try this one?
I'm a new contributor
I would start by importing the existing into the new page, ensuring it functions correctly within the layout. Then, I’d replicate the layout from the Figma design using Flexbox or Grid for the overall structure, including the table, buttons, and filters. The table will display referral details, and I’ll include interactive elements like search and filters. I’ll ensure the page is fully mobile responsive by using CSS media queries and adjusting components accordingly, such as collapsing the sidebar and stacking table elements. I’ll apply the exact colors, typography, and spacing from the Figma design for styling. Finally, I’ll implement any dynamic interactions, like sorting or filtering in the table, as required.

ETA: 2 business days (including integration, layout, styling, responsiveness, and testing).

**Comment by Ayoazeez26** [comment]
I'd love to give this a go.
I would implement the social quests page to pixel perfection using the figma file as a guide. I would also make it mobile responsive before submitting a PR

ETA - 2 days

**Comment by Akshola00** [comment]
I'd love to give this a go.

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I'll be working on issue #49.

I'll see to it that the task is completed in 3 days or less even.

**Comment by jancris100** [comment]
Would love to tackle this! I'm from dojo coding I have 2 years of experience as full stack developer and also Im actually work as mobile developer with figma

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.  This is my first time contributing to this project.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga
ETA: 2 days

**Comment by ONEONUORA** [comment]
May I pick this up?

**Comment by Amarjeet325** [comment]
I'd like to handle this task.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by JoelVR17** [comment]
## I'm Joel Vargas, and I'm a Frontend Developer
## Dojo Coding 🔥

# Implement Social Quests Page

## Description
Replicate the **Social Quests Page** as per the provided Figma design. Ensure pixel-perfect implementation, responsive design, and adherence to the Od Hackers community group guidelines. Use the pre-built sidebar located in `/frontend/app/app` folder and integrate it into the page.

---

## Requirements

### 1. **Page Layout**
- Build the **Social Quests Page** structure based on the Figma mockup.
- Import the pre-built sidebar and integrate it seamlessly into the layout.

### 2. **Responsive Design**
- Ensure the page is fully responsive across devices:
  - Desktop
  - Tablets
  - Mobile phones
- Maintain usability and aesthetic consistency at all screen sizes.

### 3. **Design Consistency**
- Match all elements in the Figma design:
  - Typography
  - Colors and spacing
  - Button styles and hover effects
  - Animations (if applicable)

### 4. **Functional Components**
- Implement necessary interactive elements, such as:
  - Clickable buttons or icons.
  - Hover states for quests.
  - Any scrollable sections or cards (if included in the mockup).

---

## Tasks

1. **Setup**
   - Import and integrate the sidebar from `/frontend/app/app`.

2. **Layout**
   - Create the page structure as shown in the Figma design.
   - Add any container elements, cards, or sections.

3. **Styling**
   - Apply styles to match the Figma design.
   - Include hover effects, button states, and any animations.

4. **Responsiveness**
   - Use CSS media queries or a responsive framework to ensure the design adapts to all screen sizes.

5. **Testing**
   - Validate functionality and responsiveness across different browsers and devices.

6. **Final Review**
   - Confirm the implementation matches the Figma design pixel-perfectly.
   - Ensure all interactions work as expected.

---

## ETA
Estimated timeline for completion:
- **Layout and structure**: ~3 hours
- **Styling and animations**: ~4-5 hours
- **Responsiveness and testing**: ~2-3 hours
- **Final review and fixes**: ~1 hour

**Total ETA**: ~10-12 hours depending on complexity.

---

## Acceptance Criteria
- The Social Quests Page matches the Figma design exactly.
- The page is fully responsive and functions across desktop, tablet, and mobile devices.
- Sidebar is correctly integrated and functional.
- Adheres to Od Hackers community group guidelines.

---

### Additional Notes
For any design or functionality clarifications, consult the project manager or refer to the Od Hackers community guidelines.

**Comment by akintola4** [comment]
I'd like to handle this task.i would love to build it , this is my  twitter account for my works https://x.com/photofola

**Comment by akintola4** [comment]
I'd like to handle this task.i would love to build it , this is my  twitter account for my works https://x.com/photofola and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me 

eta: 48hrs

**Comment by aspiringLilCoder** [comment]
Could I take a shot at this?

**Comment by DanielEmmanuel1** [comment]
@akintola4 I wanted to know your progress on the tasks
How is it going?

**Comment by akintola4** [comment]
done and already created a pr

**Comment by Dprof-in-tech** [comment]
@akintola4 , i reopended this issue because a fix was made tot he qusts file structure. kindly sync your fork with the main branch and integrate your issue solution into the new quest page structure.

There is a quests folder under /app/quests

do well to plug in yoyr solution into the socials in /app/quests/socials
