### ISSUE TITLE
FE: Build out the Leaderboard page

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#50]
https://www.figma.com/design/iW3cyAME5y74CegO0726ki/peer.protocol-quests?m=auto&t=SCxMYzYz92hgX4z3-1

here's the link to the figma and your job is to replicate exactly the Leaderboard page.
The side bar is already built out and can be found in the /frontend/app/app folder. kindly import it in the  page. Don't forget to make it mobile responsive too..

Criteria to be assigned:

follow the guidelines as given in the Od Hackers community group and dont forget to provide an ETA when applying

**Comment by omsant02** [comment]
Can I be assigned to this?

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by OWK50GA** [comment]
Mind if I take this issue?
ETA - 2 days

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. This is my first time contributing this project.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by deeseeker** [comment]
I am applying to this issue via OnlyDust platform.

Hi, I'm Qudus Adeyemi, a front-end developer with 2 years of experience. I had the opportunity to contribute to the previous OD Hackathon, where I improved the Starknet React documentation and developed a useWatchAssets hook to enhance wallet tracking functionalities and I have also contributed to Starknet Quest. I enjoy learning and tackling new challenges, and I see tackling this issue as a great way to deepen my understanding of dApps while contributing to the project.
For this, I estimate it will take around a day to complete, and I'm excited to dive into the task and collaborate with the team!

To tackle this issue, I will be doing the following:


Pay attention to responsiveness and interactivity and other specs

**Comment by 0xdevcollins** [comment]
May I take this issue on?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

ETA: 24hrs

**Comment by Yunusabdul38** [comment]
Can I jump on this task?

**Comment by ShantelPeters** [comment]
Mind if I take this issue?

**Comment by Ayoazeez26** [comment]
Can I attempt this issue?
I would implement the Leaderboard page exactly using the figma file as a guide and make sure it meets all requirements before submitting a PR
ETA - 3 days

**Comment by Akshola00** [comment]
Mind if I take this issue?

**Comment by Stephy-Crown** [comment]
Can I jump on this task?

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I'll be working on issue #50.

I envision to complete the given task in 2 days.

I'll see to it that the interface is well-built and functional, whilst maintaining a very good responsiveness across all devices.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.  This is my first time contributing to this project.

**Comment by ONEONUORA** [comment]
Can I take this issue?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with experience in both front-end and back-end development, and I would love to tackle this issue. With my proficiency in TypeScript, JavaScript and experience working on the front-end aspects of my last few hackathons, I'm confident that I can contribute to this project efficiently.

My workflow:

- Replicate the Leaderboard page exactly as per the Figma design.
- Import the existing sidebar from ```/frontend/app/app``` into the page.
- Ensure the page is fully mobile responsive.

ETA: 48 hrs

**Comment by Amarjeet325** [comment]
I'd love to work on this!

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by JoelVR17** [comment]
## I'm Joel Vargas, and I'm a Frontend Developer
## Dojo Coding 🔥

# Implement Leaderboard Page

## Description
Replicate the **Leaderboard Page** from the provided Figma design exactly. Ensure the implementation adheres to design standards and is fully responsive for desktop and mobile views. Import the pre-built sidebar from `/frontend/app/app` folder into the page.

---

## Requirements

### 1. **Page Layout**
- Build the **Leaderboard Page** as per the Figma design.
- Import and integrate the pre-built sidebar.

### 2. **Mobile Responsiveness**
- Ensure the page layout is fully responsive across various screen sizes.
- Maintain optimal readability and usability on mobile devices.

### 3. **Design Consistency**
- Match the Figma design pixel-perfectly:
  - Typography
  - Colors
  - Spacing
  - Button styles
  - Hover states and animations (if applicable)

### 4. **Functional Components**
- Implement all necessary interactive elements such as:
  - Sorting options (if provided in the design).
  - Highlighted rows or animations on interaction.

---

## Tasks

1. Import the sidebar from `/frontend/app/app`.
2. Set up the Leaderboard page structure and basic layout.
3. Build all required components as per the Figma design.
4. Add responsiveness for different screen sizes.
5. Test the design on various devices and browsers.
6. Review the design to confirm alignment with the Figma mockup.

---

## ETA
Provide an estimated timeline when applying, considering:
- **Layout and structure**: ~2-3 hours
- **Component creation and styling**: ~4-5 hours
- **Responsiveness and testing**: ~2-3 hours
- **Final review**: ~1 hour

**Total ETA**: ~9-12 hours depending on the complexity of interactions and animations.

---

## Acceptance Criteria
- The Leaderboard Page matches the Figma design exactly.
- The page is fully responsive and functional on desktop and mobile views.
- Sidebar is correctly integrated and functional.
- Adheres to the **Od Hackers community group** guidelines.

---

### Additional Notes
If any clarification or assistance is required, consult the project manager or refer to the Od Hackers community guidelines.

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me 

eta: 48hrs

**Comment by DanielEmmanuel1** [comment]
@austineblaise What's the progress on the task?
Are u having any issues?

**Comment by Dprof-in-tech** [comment]
@austineblaise , please you have one hour to make a draft PR or you will be unassigned.

**Comment by omsant02** [comment]
i would like to take this issue @Dprof-in-tech ,
would solve it in 5-6 hrs

**Comment by austineblaise** [comment]
I'm done! ...
Will make a pr before the  end of today, please!

**Comment by austineblaise** [comment]
> @austineblaise What's the progress on the task? Are u having any issues?

I'm 98% done with the design! ... Just trying to "brush up" !
Will make a pr before the  end of today, please!
Latest, tomorrow!
