### ISSUE TITLE
CONTRACT: Build a function to get all lending proposals

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#69]
This function should retrieve all the lending proposals and their counters so they can be displayed on the frontend too.

build this function and write the tests for it.

**Comment by martinvibes** [comment]
hey @Dprof-in-tech kindly assign

**Comment by emarc99** [comment]
Can I take care of this issue?

**Comment by vestor-dev** [comment]
@Dprof-in-tech can i try working on this

**Comment by martinvibes** [comment]
hey @Dprof-in-tech kindly assign

**Comment by TropicalDog17** [comment]
Can I work on this @Dprof-in-tech
