### ISSUE TITLE
Improve Navbar by Removing Arrows and Adding Hover Effects

### ISSUE THREAD

**Issue by rohitmore07** [Peerprotocol/peer-on-strk#77]
The current navbar design includes arrows that feel unnecessary and do not contribute to a seamless user experience. To enhance the design and usability, I propose the following changes :

**Remove Arrows :**
Eliminate the arrows from the navbar elements to create a cleaner and more modern look.

**Add Hover Effects :**
Introduce smooth hover effects for each navbar element.
Use transitions like color changes, underlines, or background highlights to improve interactivity and feedback for users.
These updates will enhance the navbar's visual appeal and provide a better user experience by making it more intuitive and polished.

**I'd like to work on this issue. Please assign it to me so I can start making the changes.**

**Comment by Dprof-in-tech** [comment]
not required. Thank you but its all part of the design
