### ISSUE TITLE
CI/CD- Code integration, testing and debugging

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#80]
Look through the entire cairo code, test the code integration, debug all errors and fix as encountered.

**Comment by casweeney** [comment]
## I can handle this
Considering that I have been contributing on this project since when it started, I believe that I understand the codebase well enough.

## ETA: 1 - 2 days
The errors might vary so I created enough time for any uncertainty.

**Comment by od-hunter** [comment]
Can I do this please? @Dprof-in-tech
